apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  PUBLIC_DOMAIN: gabro.ovh
  TIMEZONE: Europe/Rome
  LB_RANGE: 192.168.1.55-192.168.1.69
  BACKUP_PATH: /mnt/backups
  MEDIA_PATH: /media/gabro/Volume
  MUSIC_PATH: /home/gabro/Music
  STATELESS_NODE: pi-node
  TELEGRAM_CHAT_ID: "714757023"
  LOCAL_DOMAIN: local.gabro.ovh
  LETSENCRYPT_EMAIL: gabriele.broccoli@gmail.com
