apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  PUBLIC_DOMAIN: gabro.ovh
  TIMEZONE: Europe/Rome
  LB_RANGE: 192.168.1.55-192.168.1.100
  PRIMARY_NODE_IP: 192.168.1.10
  LAN_CIDR: 192.168.1.0/24
  LAN_SUPERNET: 192.168.0.0/16
  TRAEFIK_IP: 192.168.1.55
  ADGUARD_IP: 192.168.1.60
  ESP32_SALA_IP: 192.168.1.50
  ESP32_TAVERNA_IP: 192.168.1.51
  ESP32_GARAGE_IP: 192.168.1.52
  BACKUP_PATH: /mnt/backups
  NVME_PATH: /mnt/nvme500
  MEDIA_PATH: /media/gabro/Volume
  MUSIC_PATH: /home/gabro/Music
  PRIMARY_NODE: homelab
  STATELESS_NODE: homelab
  CLUSTER_NAME: homelab
  TELEGRAM_CHAT_ID: "714757023"
  LOCAL_DOMAIN: local.gabro.ovh
  LETSENCRYPT_EMAIL: gabriele.broccoli@gmail.com
