apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-internal
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
    - host: home.homelab.arpa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-external
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-authentik-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: home.gabro.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
