apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: radarr-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: radarr
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: sonarr-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sonarr
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lidarr-vpa
  namespace: music
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lidarr
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qbittorrent-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qbittorrent
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prowlarr-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prowlarr
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jellyseerr-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jellyseerr
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jellyfin-vpa
  namespace: jellyfin
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jellyfin
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
