apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage-config.yaml
  - homepage-deployment.yaml
  - homepage-ingress.yaml
  - homepage-middleware.yaml
  - homepage-rbac.yaml
