{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total{cluster=~\"$cluster|\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "avg(sum by (core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster|\"}[$__rate_interval])))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster|\"}) / sum(machine_cpu_cores{cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster|\"}) / sum(machine_cpu_cores{cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster|\", job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_memory_available_bytes{cluster=~\"$cluster|\"} + windows_memory_cache_bytes{cluster=~\"$cluster|\"}) / sum(windows_os_visible_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster|\"}) / sum(machine_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster|\"}) / sum(machine_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{cluster=~\"$cluster|\"}))"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{cluster=~\"$cluster|\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster|\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{cluster=~\"$cluster|\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{cluster=~\"$cluster|\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$cluster|\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster|\", job=~\"$job\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{cluster=~\"$cluster|\"} - windows_memory_available_bytes{cluster=~\"$cluster|\"} - windows_memory_cache_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Real Windows"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=~\"$cluster|\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    },
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{cluster=~\"$cluster|\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster|\", job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"})",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{cluster=~\"$cluster|\"} - windows_memory_available_bytes{cluster=~\"$cluster|\"}) / sum(windows_os_visible_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_cpu_usage_seconds_total{container_id!=\"\", cluster=~\"$cluster|\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster|\"}) OR kube_namespace_created{cluster=~\"$cluster|\"} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=~\"$cluster|\"}) by (namespace)\n+ on (namespace)\n(sum(windows_container_memory_usage_commit_bytes{container_id!=\"\", cluster=~\"$cluster|\"} * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster|\"}) OR kube_namespace_created{cluster=~\"$cluster|\"} * 0) by (namespace))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(sum by (instance,core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=~\"$cluster|\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster|\", job=~\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster|\", job=~\"$job\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{cluster=~\"$cluster|\"} - windows_memory_available_bytes{cluster=~\"$cluster|\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled by instance",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{cluster=~\"$cluster|\"}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster|\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{cluster=~\"$cluster|\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (device)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (device)",
     "legendFormat": "Transmitted : {{ device }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Received : {{ nic }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (transmit)"
    },
    {
     "expr": "sum(rate(windows_net_packets_received_discarded_total{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(windows_net_packets_outbound_discarded_total{cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_network_receive_bytes_total{container_id!=\"\", cluster=~\"$cluster|\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster|\"}) OR kube_namespace_created{cluster=~\"$cluster|\"} * 0) by (namespace))",
     "legendFormat": "Received : {{ namespace }}"
    },
    {
     "expr": "- (sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_network_transmit_bytes_total{container_id!=\"\", cluster=~\"$cluster|\"}[$__rate_interval]) * on (container_id) group_left (container, pod, namespace) max by ( container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", cluster=~\"$cluster|\"}) OR kube_namespace_created{cluster=~\"$cluster|\"} * 0) by (namespace)))",
     "legendFormat": "Transmitted : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Network Received (with all virtual devices) by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{cluster=~\"$cluster|\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (without loopback)  by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{nic!~\".*Virtual.*\",cluster=~\"$cluster|\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{nic!~\".*Virtual.*\",cluster=~\"$cluster|\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\", cluster=~\"$cluster|\", job=~\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Nodes",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster|\"}, node)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"(?i:($node)([.][a-z0-9.]+)?)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\", cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "List of pods on node ($node)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{node=~\"$node\", cluster=~\"$cluster|\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=~\"$node\", cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{node=~\"$node\", cluster=~\"$cluster|\"}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$instance\", cluster=~\"$cluster|\"} - node_boot_time_seconds{instance=~\"$instance\", cluster=~\"$cluster|\"}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]) * 100) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} - node_memory_MemFree_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} - (node_memory_Cached_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} + node_memory_Buffers_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} - node_memory_SwapFree_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=~\"$node\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$node\", image!=\"\", cluster=~\"$cluster|\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of CPU Core Throttled",
   "type": "timeseries",
   "description": "Number of times a CPU core has been throttled on an instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Nb of cpu core throttles"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Context Switches & Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "Allocated file descriptors"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network usage (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_errs_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network usage (packet/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_packets_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network total drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "TCP Currently Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "TCP Currently Established"
    }
   ]
  },
  {
   "title": "NF Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "NF Conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$instance\", cluster=~\"$cluster|\"}",
     "legendFormat": "NF Conntrack limit"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_inodes_used{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{node=~\"$node\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim) * 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "FS usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance\", cluster=~\"$cluster|\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "FS inode usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_files_free{instance=~\"$instance\", cluster=~\"$cluster|\"} / node_filesystem_files{instance=~\"$instance\", cluster=~\"$cluster|\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Reads by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed reads by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "read/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed writes by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "write/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk(s) io/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_now{instance=~\"$instance\", cluster=~\"$cluster|\"}[$__rate_interval]) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "FS - Device Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_device_error{instance=~\"$instance\", cluster=~\"$cluster|\"}) by (mountpoint)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Namespaces",
 "description": "This is a modern 'Namespaces View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster|\"}, namespace)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "created_by",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"},created_by_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace(s) usage on total cluster CPU in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) / sum(machine_cpu_cores{cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "Namespace(s) usage on total cluster RAM in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\", cluster=~\"$cluster|\"}) / sum(machine_memory_bytes{cluster=~\"$cluster|\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Network Policies"
    }
   ]
  },
  {
   "title": "Namespace(s) CPU Usage in cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\", cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\", cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$cluster|\"})",
     "legendFormat": "Cluster Total"
    }
   ]
  },
  {
   "title": "Namespace(s) RAM Usage in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\", cluster=~\"$cluster|\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\", cluster=~\"$cluster|\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\", cluster=~\"$cluster|\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$cluster|\"})",
     "legendFormat": "Cluster Total"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{cluster=~\"$cluster|\"}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace, pod",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{namespace=~\"$${namespace}\", cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace, pod) > 0",
     "legendFormat": "namespace: {{ namespace }} - pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace, pod",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$${namespace}\", cluster=~\"$cluster|\"}[$__rate_interval])) by (namespace, pod) > 0",
     "legendFormat": "namespace: {{ namespace }} - pod: {{ pod }}"
    }
   ]
  },
  {
   "title": "Nb of pods by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Restarts Total"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\", cluster=~\"$cluster|\"})",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Nb of containers by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replicas available by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Replicas unavailable by deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Pods with unexpected status",
   "type": "timeseries",
   "description": "List of pods that are not in Running or Succeeded status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running|Succeeded\", namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (pod) > 0",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Container Image Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (image)",
     "legendFormat": "{{ image }}"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Persistent Volumes - Capacity and usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Capacity and usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }} - Used"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }} - Capacity"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(kubelet_volume_stats_inodes_used{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{namespace=~\"$namespace\", cluster=~\"$cluster|\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Network - Bandwidth by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received - {{ pod }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted - {{ pod }}"
    }
   ]
  },
  {
   "title": "Network - Packets Rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received - {{ pod }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted - {{ pod }}"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received - {{ pod }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted - {{ pod }}"
    }
   ]
  },
  {
   "title": "Network - Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Received - {{ pod }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{namespace=~\"$namespace\", pod=~\"$${created_by}.*\", cluster=~\"$cluster|\"}[$__rate_interval])) by (pod)",
     "legendFormat": "Transmitted - {{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Pods",
 "description": "This is a modern 'Pods View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster|\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", cluster=~\"$cluster|\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created by",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Priority Class",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$pod\", priority_class!=\"\", cluster=~\"$cluster|\"}",
     "legendFormat": "{{ priority_class }}"
    }
   ]
  },
  {
   "title": "QOS Class",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_status_qos_class{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"} > 0",
     "legendFormat": "{{ qos_class }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Last Terminated Exit Code",
   "type": "stat",
   "description": "Panel only works when a single pod is selected.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_exitcode{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total pod CPU Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod CPU Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1))",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Total pod RAM Requests usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Total pod RAM Limits usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster|\"}) by (container)"
    }
   ]
  },
  {
   "title": "CPU Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)",
     "legendFormat": "{{ container }}  REQUESTS"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"cpu\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)",
     "legendFormat": "{{ container }}  LIMITS"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", cluster=~\"$cluster|\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", resource=\"memory\", job=~\"$job\", cluster=~\"$cluster|\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\", pod=~\"$pod\", job=~\"$job\", cluster=~\"$cluster|\"} == 1)) by (container)",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "CPU Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster|\"}) by (container, id)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "OOM Events by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{namespace=\"$${namespace}\", pod=~\"$${pod}\", container!=\"\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container) > 0",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Container Restarts by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$${namespace}\", pod=~\"$${pod}\", container!=\"\", job=~\"$job\", cluster=~\"$cluster|\"}[$__rate_interval])) by (container) > 0",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Pods with Container Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=~\"ErrImagePull|ImagePullBackOff|CrashLoopBackOff\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "kube_pod_status_scheduled{condition=\"false\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{namespace=~\"$namespace\", pod=~\"$pod\", cluster=~\"$cluster|\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}