apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1h
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.9.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 12h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    global:
      image:
        registry: ghcr.io
    crds:
      install: true
    features:
      policyExceptions:
        enabled: true
        namespace: kyverno
    config:
      resourceFiltersInclude:
        - '[*/*,flux-system,*]'
        - '[*/*,longhorn-system,*]'
        - '[*/*,metallb-system,*]'
        - '[*/*,system-upgrade,*]'
    admissionController:
      replicas: 1
      container:
        resources:
          requests:
            cpu: 50m
            memory: 192Mi
          limits:
            cpu: 500m
            memory: 512Mi
    reportsController:
      enabled: true
      replicas: 1
      container:
        resources:
          requests:
            cpu: 20m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 384Mi
    backgroundController:
      enabled: false
    cleanupController:
      enabled: false
