apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nextcloud-postgresql-vpa
  namespace: nextcloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nextcloud-postgresql
  updatePolicy:
    updateMode: "Off"