apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: backup-secrets
    creationPolicy: Owner
  data:
    - secretKey: restic-password
      remoteRef:
        key: immich/backup-secrets/restic-password
    - secretKey: immich-db-password
      remoteRef:
        key: immich/backup-secrets/immich-db-password
