apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-s3
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: nextcloud-s3
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: nextcloud/nextcloud-s3/S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: nextcloud/nextcloud-s3/S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: nextcloud-db
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: nextcloud/nextcloud-db/db-username
    - secretKey: db-password
      remoteRef:
        key: nextcloud/nextcloud-db/db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: nextcloud-redis
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: nextcloud/nextcloud-redis/redis-password
