apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dispatcharr.yaml
  - ingress.yaml
  - prowlarr.yaml
  - qbittorrent.yaml
  - radarr.yaml
  - seerr.yaml
  - servarr-vpa.yaml
  - sonarr.yaml
