apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared/tunnel-token/token
