apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: authentik-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: authentik/authentik-credentials/postgresql-password
    - secretKey: secret-key
      remoteRef:
        key: authentik/authentik-credentials/secret-key
