apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-externalsecret.yaml
  - authentik-fw-middleware.yaml
  - authentik-helmrelease.yaml
  - authentik-ingress.yaml
  - authentik-vpa.yaml
