apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pankha
components:
  - ../components/default-deny-egress
  - ../components/default-deny-ingress
  - ../components/allow-dns
  - ../components/allow-prometheus-scrape
resources:
  - policies.yaml
