apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: centralino
resources:
  - authentik-forward-auth.yaml
  - centralino.yaml
  - centralino-ingress.yaml
configMapGenerator:
  - name: centralino-nginx
    files:
      - default.conf=nginx.conf
  - name: centralino-site
    files:
      - index.html=site/index.html
