apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: lidarr-vpa
  namespace: music
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lidarr
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
