apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nextcloud-cron.yaml
  - nextcloud-externalsecret.yaml
  - nextcloud-helmrelease.yaml
  - nextcloud-hpa.yaml
  - nextcloud-hsts.yaml
  - nextcloud-pdb.yaml
  - nextcloud-vars-externalsecret.yaml
  - nextcloud-vpa.yaml
