apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
spec:
  refreshInterval: 6h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: nextcloud-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXTCLOUD_ADMIN_USER
      remoteRef:
        key: nextcloud/nextcloud-secrets/NEXTCLOUD_ADMIN_USER
    - secretKey: NEXTCLOUD_ADMIN_PASSWORD
      remoteRef:
        key: nextcloud/nextcloud-secrets/NEXTCLOUD_ADMIN_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: nextcloud/nextcloud-secrets/POSTGRES_PASSWORD
