apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
  namespace: flux-system
spec:
  refreshInterval: 12h15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: github-webhook-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: flux-system/github-webhook-token/token
