apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  refreshInterval: 12h55m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: immich-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: immich/immich-secrets/DB_PASSWORD
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: immich/immich-secrets/POSTGRES_PASSWORD
