apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: music
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: lidarr.homelab.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr
            port:
              number: 8686
