apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appapi-secret
  namespace: nextcloud
spec:
  refreshInterval: 6h20m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: appapi-secret
    creationPolicy: Owner
  data:
    - secretKey: haproxy-password
      remoteRef:
        key: nextcloud/appapi-secret/haproxy-password
