apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./adguard
  - ./authentik
  - ./backup
  - ./centralino
  - ./cloudflared
  - ./external-secrets
  - ./immich
  - ./jellyfin
  - ./matrix
  - ./minio
  - ./monitoring
  - ./music
  - ./nextcloud
  - ./pankha
