apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      spec:
        loadBalancerIP: ${TRAEFIK_IP}
    ports:
      web:
        transport:
          respondingTimeouts:
            readTimeout: 30m
      websecure:
        transport:
          respondingTimeouts:
            readTimeout: 30m
