apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volsync-helmrelease.yaml
  - longhorn-volumesnapshotclass.yaml
  - volsync-servicemonitor.yaml
  - longhorn-single-storageclass.yaml
