apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Rome"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi 
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
          livenessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /ping
              port: 7878
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: config
          hostPath:
            path: /var/lib/radarr
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /media/gabro/Volume
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: jellyfin
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
