apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: centralino
components:
  - ../components/default-deny-egress
  - ../components/default-deny-ingress
  - ../components/allow-dns
  - ../components/allow-ingress-from-traefik
resources:
  - policies.yaml
