apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
components:
  - ../components/default-deny-egress
  - ../components/default-deny-ingress
  - ../components/allow-dns
  - ../components/allow-prometheus-scrape
  - ../components/allow-egress-intra-namespace
  - ../components/allow-intra-namespace
  - ../components/allow-egress-to-restic-rest-server
  - ../components/allow-egress-to-authentik
resources:
  - policies.yaml
