apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-creds
  namespace: immich
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: restic-creds
    creationPolicy: Owner
  data:
    - secretKey: rest-writer-user
      remoteRef:
        key: backup/restic-rest-server/writer-user
    - secretKey: rest-writer-password
      remoteRef:
        key: backup/restic-rest-server/writer-password
    - secretKey: immich-db-password
      remoteRef:
        key: backup/restic-immich-db/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-creds
  namespace: nextcloud
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: restic-creds
    creationPolicy: Owner
  data:
    - secretKey: rest-writer-user
      remoteRef:
        key: backup/restic-rest-server/writer-user
    - secretKey: rest-writer-password
      remoteRef:
        key: backup/restic-rest-server/writer-password
    - secretKey: nextcloud-db-password
      remoteRef:
        key: backup/restic-nextcloud-db/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-creds
  namespace: authentik
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: restic-creds
    creationPolicy: Owner
  data:
    - secretKey: rest-writer-user
      remoteRef:
        key: backup/restic-rest-server/writer-user
    - secretKey: rest-writer-password
      remoteRef:
        key: backup/restic-rest-server/writer-password
    - secretKey: authentik-db-password
      remoteRef:
        key: backup/restic-authentik-db/password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-admin-creds
  namespace: backup
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: restic-admin-creds
    creationPolicy: Owner
  data:
    - secretKey: rest-admin-user
      remoteRef:
        key: backup/restic-rest-server/admin-user
    - secretKey: rest-admin-password
      remoteRef:
        key: backup/restic-rest-server/admin-password
    - secretKey: immich-files-password
      remoteRef:
        key: backup/restic-immich-files/password
    - secretKey: immich-db-password
      remoteRef:
        key: backup/restic-immich-db/password
    - secretKey: nextcloud-db-password
      remoteRef:
        key: backup/restic-nextcloud-db/password
    - secretKey: nextcloud-minio-password
      remoteRef:
        key: backup/restic-nextcloud-minio/password
    - secretKey: authentik-db-password
      remoteRef:
        key: backup/restic-authentik-db/password
