apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-cronjobs.yaml
  - backup-externalsecret.yaml
  - backup-prometheusrule.yaml
  - restic-rest-server.yaml
  - restic-rest-server-externalsecret.yaml
  - restic-exporter.yaml
  - restic-prune-cronjob.yaml
  - system-cleanup.yaml
  - volsync-immich.yaml
  - volsync-minio.yaml
