apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-rest-server-creds
  namespace: backup
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: restic-rest-server-creds
    creationPolicy: Owner
  data:
    - secretKey: writer-user
      remoteRef:
        key: backup/restic-rest-server/writer-user
    - secretKey: writer-password
      remoteRef:
        key: backup/restic-rest-server/writer-password
    - secretKey: admin-user
      remoteRef:
        key: backup/restic-rest-server/admin-user
    - secretKey: admin-password
      remoteRef:
        key: backup/restic-rest-server/admin-password
