apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic-adguard
  namespace: adguard
spec:
  refreshInterval: 12h50m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: volsync-restic-adguard
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "rest:http://{{ .writerUser }}:{{ .writerPassword }}@restic-rest-server.backup.svc.cluster.local:8000/adguard"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
  data:
    - secretKey: writerUser
      remoteRef:
        key: backup/restic-rest-server/writer-user
    - secretKey: writerPassword
      remoteRef:
        key: backup/restic-rest-server/writer-password
    - secretKey: resticPassword
      remoteRef:
        key: backup/restic-adguard/password
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: adguard
  namespace: adguard
spec:
  sourcePVC: adguard-pvc
  trigger:
    schedule: "30 7 */3 * *"
  restic:
    repository: volsync-restic-adguard
    copyMethod: Direct
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn-single
    pruneIntervalDays: 3650
    retain:
      daily: 7
      weekly: 4
      monthly: 12
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    moverResources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: adguardhome
            topologyKey: kubernetes.io/hostname
