apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-adguard
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared-adguard
  template:
    metadata:
      labels:
        app: cloudflared-adguard
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: adguard-tunnel-token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
          livenessProbe:
            exec:
              command:
                - cloudflared
                - tunnel
                - --version
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
