apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-clipcascade
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared-clipcascade
  template:
    metadata:
      labels:
        app: cloudflared-clipcascade
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: clipcascade-tunnel-token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run