apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
labels:
  - pairs:
      repo: immich-db
    includeSelectors: true
patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /metadata/name
        value: restic-exporter-immich-db
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "rest:http://$(REST_USER):$(REST_PASSWORD)@restic-rest-server.backup.svc.cluster.local:8000/immich-db"
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/key
        value: immich-db-password
