recommender:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

updater:
  extraArgs:
    feature-gates: InPlaceOrRecreate=true
    min-replicas: "1"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

admissionController:
  extraArgs:
    feature-gates: InPlaceOrRecreate=true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
