apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard
  - authentik
  - backup
  - cloudflared
  - grafana
  - headlamp
  - homepage
  - immich
  - jellyfin
  - lidarr
  - loki
  - minio
  - navidrome
  - nextcloud
  - nut-exporter
  - prometheus
  - servarr
  - traefik
