apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard/ks.yaml
  - alloy/ks.yaml
  - authentik/ks.yaml
  - backup/ks.yaml
  - cert-manager-config/ks.yaml
  - cloudflared/ks.yaml
  - flux-webhook/ks.yaml
  - grafana/ks.yaml
  - headlamp/ks.yaml
  - homepage/ks.yaml
  - immich/ks.yaml
  - jellyfin/ks.yaml
  - lidarr/ks.yaml
  - longhorn/ks.yaml
  - loki/ks.yaml
  - minio/ks.yaml
  - navidrome/ks.yaml
  - nextcloud/ks.yaml
  - nut-exporter/ks.yaml
  - pankha/ks.yaml
  - prometheus/ks.yaml
  - servarr/ks.yaml
  - traefik/ks.yaml
