apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - synapse.yaml
  - element-web.yaml
  - mas.yaml
  - matrix-externalsecret.yaml
  - mas-externalsecret.yaml
  - matrix-ingress.yaml
