apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas-config
  namespace: matrix
spec:
  refreshInterval: 14h55m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mas-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          http:
            public_base: "https://account.${PUBLIC_DOMAIN}/"
            listeners:
              - name: web
                resources:
                  - name: discovery
                  - name: human
                  - name: oauth
                  - name: compat
                  - name: graphql
                  - name: assets
                binds:
                  - address: "[::]:8080"
              - name: internal
                resources:
                  - name: health
                  - name: prometheus
                binds:
                  - address: "[::]:8081"
          database:
            host: matrix-postgres
            port: 5432
            username: mas
            password: "{{ .POSTGRES_PASSWORD }}"
            database: mas
          matrix:
            homeserver: "matrix.${PUBLIC_DOMAIN}"
            endpoint: "http://synapse:8008/"
            secret: "{{ .MATRIX_SECRET }}"
          secrets:
            encryption: "{{ .ENCRYPTION_SECRET }}"
            keys:
              - key_file: /config/rsa.key
          passwords:
            enabled: true
            schemes:
              - version: 1
                algorithm: bcrypt
                unicode_normalization: true
              - version: 2
                algorithm: argon2id
          account:
            password_registration_enabled: true
            password_registration_token_required: true
            password_registration_email_required: false
            email_change_allowed: false
        rsa.key: "{{ .RSA_PRIVATE_KEY }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: matrix/mas-secrets/POSTGRES_PASSWORD
    - secretKey: MATRIX_SECRET
      remoteRef:
        key: matrix/mas-secrets/MATRIX_SECRET
    - secretKey: ENCRYPTION_SECRET
      remoteRef:
        key: matrix/mas-secrets/ENCRYPTION_SECRET
    - secretKey: RSA_PRIVATE_KEY
      remoteRef:
        key: matrix/mas-secrets/RSA_PRIVATE_KEY
