apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: matrix.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse
                port:
                  number: 8008
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mas-compat
  namespace: matrix
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`matrix.${PUBLIC_DOMAIN}`) && PathRegexp(`^/_matrix/client/[a-zA-Z0-9._-]+/(login|logout|refresh)`)
      kind: Rule
      services:
        - name: mas
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mas-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: account.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mas
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: element-web-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: chat.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: element-web
                port:
                  number: 80
