apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-config
  namespace: matrix
spec:
  refreshInterval: 14h55m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: synapse-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        homeserver.yaml: |
          server_name: "matrix.${PUBLIC_DOMAIN}"
          public_baseurl: "https://matrix.${PUBLIC_DOMAIN}/"
          pid_file: "/tmp/homeserver.pid"
          signing_key_path: "/data/homeserver.signing.key"
          media_store_path: "/data/media_store"
          log_config: "/config/log.config"
          report_stats: false
          listeners:
            - port: 8008
              tls: false
              type: http
              x_forwarded: true
              bind_addresses: ["0.0.0.0"]
              resources:
                - names: [client]
                  compress: false
          database:
            name: psycopg2
            args:
              user: synapse
              password: "{{ .POSTGRES_PASSWORD }}"
              dbname: synapse
              host: matrix-postgres
              port: 5432
              cp_min: 5
              cp_max: 10
          macaroon_secret_key: "{{ .MACAROON_SECRET_KEY }}"
          form_secret: "{{ .FORM_SECRET }}"
          registration_shared_secret: "{{ .REGISTRATION_SHARED_SECRET }}"
          enable_registration: false
          federation_domain_whitelist: []
          allow_public_rooms_over_federation: false
          trusted_key_servers: []
          max_upload_size: "100M"
          url_preview_enabled: false
        log.config: |
          version: 1
          formatters:
            precise:
              format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
          handlers:
            console:
              class: logging.StreamHandler
              formatter: precise
          loggers:
            synapse.storage.SQL:
              level: INFO
          root:
            level: INFO
            handlers: [console]
          disable_existing_loggers: false
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: matrix/matrix-secrets/POSTGRES_PASSWORD
    - secretKey: MACAROON_SECRET_KEY
      remoteRef:
        key: matrix/matrix-secrets/MACAROON_SECRET_KEY
    - secretKey: FORM_SECRET
      remoteRef:
        key: matrix/matrix-secrets/FORM_SECRET
    - secretKey: REGISTRATION_SHARED_SECRET
      remoteRef:
        key: matrix/matrix-secrets/REGISTRATION_SHARED_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-postgres
  namespace: matrix
spec:
  refreshInterval: 14h55m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: matrix-postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: matrix/matrix-secrets/POSTGRES_PASSWORD
