apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: matrix.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse
                port:
                  number: 8008
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mas-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: account.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mas
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: element-web-external
  namespace: matrix
spec:
  ingressClassName: traefik
  rules:
    - host: chat.${PUBLIC_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: element-web
                port:
                  number: 80
