apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-oauth
  namespace: monitoring
spec:
  refreshInterval: 13h10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: grafana-authentik-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: monitoring/grafana-authentik-oauth/client-id
    - secretKey: client-secret
      remoteRef:
        key: monitoring/grafana-authentik-oauth/client-secret
