apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: c8536524-d9a3-48f5-a4cf-b41600bd0ee6
      projectID: eb7f19cd-99ea-4888-95f7-b41600be7baf
      caProvider:
        type: ConfigMap
        name: bitwarden-sdk-server-ca
        namespace: external-secrets
        key: ca.crt
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
