apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflared
  labels:
    app.kubernetes.io/component: tunnel
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: tunnel
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tunnel
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app]
          targetLabel: tunnel
          regex: cloudflared-(.+)
          replacement: $1
