apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  refreshInterval: 13h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
  data:
    - secretKey: bot-token
      remoteRef:
        key: monitoring/alertmanager-telegram/bot-token
