apiVersion: v1
kind: Service
metadata:
  name: restic-exporter
  namespace: backup
  labels:
    app: restic-exporter
spec:
  selector:
    app: restic-exporter
  ports:
    - port: 8001
      targetPort: 8001
      name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restic-exporter
  namespace: backup
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: restic-exporter
  endpoints:
    - port: metrics
      path: /
      interval: 60s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_repo]
          action: replace
          targetLabel: repo
